### ISSUE TITLE
Distribution via CocoaPods

### ISSUE THREAD

**Issue by wvteijlingen** [MakeAWishFoundation/SwiftyMockyCLI#11]
Since SwiftyMocky distributes its runtime via CocoaPods, it would be nice if there was also a pod that contained the CLI. Alternatively the CLI executable could be contained in the main SwiftyMocky pod.

Tools like SwiftLint also support installation of the CLI via CocoaPods, which makes it very easy to automate the installation for a project that already uses CocoaPods for its dependencies.

This way, it's much easier to keep the versions of runtime and the CLI in sync, and removes the need for yet another package manager (Mint).

See the SwiftLint podspec for an example: https://github.com/realm/SwiftLint/blob/master/SwiftLint.podspec

**Comment by g-amichnia** [comment]
Thanks for the tip, I will look into it.

**Comment by luvacu** [comment]
Are there any updates regarding this? Installing SwiftyMocky CLI in our CI takes an extra 4-5 minutes. Any way we can help?

**Comment by iainmerrick** [comment]
This is causing trouble for me too. The initial Mint install is OK, but the swiftymocky exe recursively invokes Mint to install sourcery, and that step is breaking on our build (CircleCI).

Right now I'm just trying to avoid that recursive Mint invocation. I plan to leverage SPM to get the sourcery executable, so it will just be built alongside swiftymocky. The main obstacle is version skew — I need to tweak Sourcery's package info a bit, but SwiftyMockyCLI depends on an older version of Sourcery due to some of its other dependencies, so I'll probably need to update those.

If I can get that working, it should be possible to make a nice CocoaPods build with no Mint dependency at all.

**Comment by wvteijlingen** [comment]
@iainmerrick 

Now that you mentioned it, I ran into some weirdness on CI as well when I tried to use Mint. Never really dug into it, but this sounds like the exact same problem I had back then.

> the swiftymocky exe recursively invokes Mint to install sourcery

If I understand correctly: If I don't have sourcery installed, swiftymocky tries to install it when invoked?

To be honest, that sounds a bit hacky to me. I wouldn't want any package to just go ahead and install other packages. Seems much cleaner to just specify the dependency in the readme and exit swiftymocky with installation instructions if sourcery is not installed yet.

If I'm correct that would also solve your problem.

**Comment by iainmerrick** [comment]
Right, my thoughts exactly!

My attempted SPM workaround (make it build both executables together) doesn't seem to be working. Your suggestion of just requiring Sourcery to be preinstalled is a lot simpler. I'll give that a shot.

**Comment by iainmerrick** [comment]
Aha, it looks like you can avoid the Mint call just by overriding sourceryCommand in your Mockfile.

**Comment by iainmerrick** [comment]
Just to close the loop on this, this line in Mockfile is working well for me:

`sourceryCommand: ./Pods/Sourcery/bin/sourcery`

A CocoaPods installation option (like Sourcery itself) would still be a useful improvement.

**Comment by wvteijlingen** [comment]
I just saw that the CLI was moved back to the main repo, and can now be invoked with `./Pods/SwiftyMocky/bin/swiftymocky generate`.

Love it, thanks!
